### ISSUE TITLE
ogg-iOS usage

### ISSUE THREAD

**Issue by calvinsug** [obaskanderi/Ogg-iOS#1]
Hi, just wondering how to use this framework ? I have trouble to play ogg audio file in Swift using AVAudioPlayer, is it possible to use this framework to play ogg audio format?

**Comment by obaskanderi** [comment]
I used this framework to help encode audio into ogg file format. For an example on how I used it you could checkout:

https://github.com/obaskanderi/OpusRecorder/blob/master/OpusRecorder/Classes/Encoder.swift

For playback I have used https://github.com/ap4y/OrigamiEngine maybe try that out.
